apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: app-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-container
  template:
    metadata:
      labels:
        name: nginx-container
    spec:
      containers:
        - image: nginx
          name: nginx
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 256Mi
            requests:
              cpu: 0.5
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-proxy
  name: nginx-service
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31585
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    name: nginx-container
  sessionAffinity: None
  type: LoadBalancer
